services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: pip install -r requirements.txt -i https://pypi.org/simple --timeout=100
    startCommand: gunicorn app:app --bind 0.0.0.0:5000
