services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:10000
    envVars:
      - key: SECRET_KEY
        value: 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 # Replace with your actual secret key
